x-airflow-common:
  &airflow-common
  image: apache/airflow:2.8.1-python3.10
  environment:
    &airflow-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth'
    _AIRFLOW_WWW_USER_USERNAME: airflow
    _AIRFLOW_WWW_USER_PASSWORD: airflow
    PYTHONPATH: /opt/airflow/dags:/opt/airflow/bookshop
  volumes:
    - ./airflow/dags:/opt/airflow/dags
    - ./airflow:/opt/airflow/logs
    - ./dbt:/opt/dbt
    - ./bookshop:/opt/airflow/bookshop   # 🔥 Monte ton dossier "bookshop" ici
  depends_on:
    - postgres

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data

  airflow-init:
    <<: *airflow-common
    command: ["airflow", "db", "init"]

  webserver:
    <<: *airflow-common
    ports:
      - "8082:8080"
    command: webserver
    restart: always

  scheduler:
    <<: *airflow-common
    command: scheduler
    restart: always

  dbt:
    image: ghcr.io/dbt-labs/dbt-postgres:1.6.4
    container_name: dbt
    volumes:
      - ./dbt:/usr/app
    working_dir: /usr/app
    entrypoint: ["tail", "-f", "/dev/null"]

volumes:
  postgres-db-volume:
