name: bookshop_dbt
version: '1.0.0'
profile: bookshop

# Définition des chemins des modèles et des autres dossiers
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Cibles de nettoyage des résultats de la construction DBT
clean-targets:
  - "target"
  - "dbt_packages"

# Configuration des modèles et des schémas
models:
  bookshop_dbt:
    stagging:
      +schema: stagging
      +materialized: table
    warehouse:
      +schema: warehouse
      +materialized: table
    marts:
      +schema: marts
      +materialized: table
